# Generated by Django 5.0.7 on 2024-08-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='conf_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profilePicture/<django.db.models.fields.CharField>/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
