name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        DEBUG: ${{ secrets.DEBUG }}
        GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
        GITHUB_SECRET: ${{ secrets.GH_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        SOCIAL_AUTH_PASSWORD: ${{ secrets.SOCIAL_AUTH_PASSWORD }}
        GOOGLE_CLIENT_PASSWORD: ${{ secrets.GOOGLE_CLIENT_PASSWORD }}

      run: |
        cd GAEN
        pytest
